spring.application.name=mini_to-do_list

# port tomcat
server.port=8081

# mysql set
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.url=${spring_datasource_url}
spring.datasource.username=${spring_datasource_username}
spring.datasource.password=${spring_datasource_password}

#encoding
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

#jpa
spring.jpa.generate-ddl=true
#spring.jpa.hibernate.ddl-auto=create
spring.jpa.database=mysql
spring.jpa.show-sql=true